# =============================================================================
# Desktop
# =============================================================================

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

[theme]
builtin = "Tokyo-Night"
community_palette = "Mine"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "muted"


# -----------------------------------------------------------------------------
# Wallpaper
# -----------------------------------------------------------------------------

[wallpaper]
directory = "~/.repo/wallpapers"
transition = ["fade"]

[wallpaper.default]
path = "~/.repo/wallpapers/mountain-night.jpg"


# -----------------------------------------------------------------------------
# Location & Weather
# -----------------------------------------------------------------------------

[location]
auto_locate = true

[weather]
enabled = true
