# yazi config
# modified only, default applies otherwise
# for default config, see: https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi-default.toml

[mgr]
ratio       = [ 1, 4, 4 ]
show_hidden = true
linemode    = "size"
