# Background Wallpaper

# ──────────────
# Path Declaration
$defaultPath = ~/.config/wallpapers/mountain-night.jpg

# ──────────────
# Set
wallpaper {
    monitor = DP-1
    path = $defaultPath
}
splash = false
